services:
  postgres:
    image: postgres:18
    volumes:
      - kroll_pgdata:/var/lib/postgresql/
    environment:
      POSTGRES_DB: krolldb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d krolldb" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kroll-net
    restart: always

volumes:
  kroll_pgdata:


networks:
  kroll-net:
    name: kroll-net
    driver: bridge
