spring:
  application:
    name: kroll
  profiles:
    active: ${KROLL_PROFILE:prod}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  spring:
    autoconfigure:
      exclude:
        - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  error:
    whitelabel:
      enabled: false
  servlet:
    context-path: ""

auth:
  jwt:
    # secrets are *required* to be Base64 encoded
    secret: ${KROLL_JWT_SECRET:${KROLL_JWT_SECRET_FILE:}}
    expiration: ${KROLL_JWT_EXPIRATION:1h}
  refresh:
    expiration: ${KROLL_REFRESH_EXPIRATION:30d}
  api-key:
    max-lifetime: ${KROLL_API_KEY_MAX_LIFETIME:365d}
    default-lifetime: ${KROLL_API_KEY_DEFAULT_LIFETIME:30d}

cors:
  origins: ${KROLL_CORS_ORIGINS:http://localhost:8080}
