spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${KROLL_DB_URL:}
    username: ${KROLL_DB_USER:}
    password: ${KROLL_DB_PASSWORD:${KROLL_DB_PASSWORD_FILE:}}

springdoc:
  api-docs:
    enabled: false

logging:
  level:
    com.collederas.kroll: ${KROLL_LOG_LEVEL:INFO}
