spring:
    application:
        name: kroll
    jpa:
        hibernate:
            ddl-auto: validate
    flyway:
        enabled: true

auth:
    jwt:
        expiration: 1h
    refresh:
        expiration: 30d
    api-key:
        max-lifetime: 30d
