spring:
  application:
    name: kroll
  datasource:
    url: jdbc:postgresql://localhost:5432/krolldb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migrations

auth:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 1h

logging:
  level:
    com.collederas.kroll: ${LOG_LEVEL}